#!/bin/bash
################################################################################
# Global Variables
################################################################################
orgName="orgName" #Change this to be the name of your organization
daemon="/Library/LaunchDaemons/com.$orgName.fileVaultListener.plist"

################################################################################
# Defining Functions
################################################################################
function writeDaemon() {
#Writing LaunchDaemon
/bin/cat << EOF > "$daemon"
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Label</key>
	<string>com.$orgName.fileVaultListener</string>
	<key>RunAtLoad</key>
	<true/>
	<key>StartInterval</key>
	<integer>30</integer>
	<key>UserName</key>
	<string>root</string>
	<key>ProgramArguments</key>
	<array>
		<string>/bin/zsh</string>
		<string>/usr/local/$orgName/bin/fileVaultListener</string>
	</array>
	<key>StandardErrorPath</key>
	<string>/var/tmp/listener.err</string>
	<key>StandardOutPath</key>
	<string>/var/tmp/listener.out</string>
</dict>
</plist>
EOF
}


function setPermissions() {
#Setting permissions
	echo "Setting LaunchDaemon permissions" 
	/bin/chmod 644 "$daemon"
	/usr/sbin/chown root:wheel "$daemon"	
}

function loadDaemon() {
#Loading Daemon
	daemonLoaded=$(/bin/launchctl list | grep "com.$orgName.fileVaultListener")
	if [[ -z "$daemonLoaded" ]]; then
		echo "Loading LaunchDaemon" 
		/bin/launchctl load "$daemon"
	elif [[ -n "$daemonLoaded" ]]; then
		echo "Daemon loaded"
	fi
}

################################################################################
# Begin - HOLD ONTO BUTTS
################################################################################
writeDaemon
setPermissions
loadDaemon
exit 0


